### ISSUE TITLE
Missing cocoapod

### ISSUE THREAD

**Issue by JoeFerrucci** [artsy/Artsy-UILabels#14]
I cloned the repo, created a Podfile and ran `pod install`. I suspected this might happen because I failed to find Artsy+UILabels in the cocoapods.org search. My Podfile looks like this:

```
pod "Artsy+UILabels"
xcodeproj 'Example/Artsy+UILabels.xcodeproj'
```

Not sure what I'm doing wrong, and I'm not sure why I can't find this library in the cocoapods repo. Thanks.

**Comment by alloy** [comment]
It’s in our own spec repo, I’ve updated the README’s installation section to reflect current CocoaPods practices to include it.

**Comment by JoeFerrucci** [comment]
What's the purpose of cloning the repo and running the Example app? I did that and its just a white screen. I'm sure I'm missing something.
